import medicine from "./assets/home/medicine.svg";
import product1 from "./assets/home/product1.png";
import product2 from "./assets/home/product2.png";
import product3 from "./assets/home/product3.png";
import test1 from "./assets/testimonial/test1.jpeg";
import test2 from "./assets/testimonial/test2.webp";
import test3 from "./assets/testimonial/test3.webp";
import test4 from "./assets/testimonial/test4.webp";
import test5 from "./assets/testimonial/test5.jpeg";
import test6 from "./assets/testimonial/test6.webp";
import blog1 from "./assets/home/blog1.jpg";
import post1 from "./assets/home/post1.jpeg";
import post2 from "./assets/home/post2.jpeg";
import post3 from "./assets/home/post3.jpeg";
import post4 from "./assets/home/post4.jpeg";
import post5 from "./assets/home/post5.jpeg";
import post6 from "./assets/home/post6.jpeg";
import rate from "./assets/about/rate.png";
import employee from "./assets/about/employee.png";
import globalcustomer from "./assets/about/globalcustomer.png";
import premiumproducts from "./assets/about/premiumproducts.png";
import team1 from "./assets/about/team1.jpg";
import team2 from "./assets/about/team2.jpg";
import team3 from "./assets/about/team3.jpg";
import team4 from "./assets/about/team4.jpg";
import team5 from "./assets/about/team5.jpg";
import team6 from "./assets/about/team6.jpg";

export const categories = [
  {
    id: "1",
    name: "Medical Supplies",
    slug: "medical-supplies",
    description: "Essential medical consumables and protective products.",
    image: medicine,
    parentCategory: null,
    isPublished: true,
  },
  {
    id: "2",
    name: "Medical Devices",
    slug: "medical-devices",
    description: "Healthcare devices and medical equipment.",
    image: medicine,
    parentCategory: null,
    isPublished: true,
  },
  {
    id: "3",
    name: "Diagnostics",
    slug: "diagnostics",
    description: "Diagnostic and monitoring equipment.",
    image: medicine,
    parentCategory: null,
    isPublished: true,
  },
  {
    id: "4",
    name: "Pharmaceuticals",
    slug: "pharmaceuticals",
    description: "Medicines and pharmaceutical products.",
    image: medicine,
    parentCategory: null,
    isPublished: true,
  },
  {
    id: "5",
    name: "Hospital Essentials",
    slug: "hospital-essentials",
    description: "Products required for hospitals and clinics.",
    image: medicine,
    parentCategory: null,
    isPublished: true,
  },
];

export const products = [
  {
    id: "1",
    title: "FCVH Surgical Gloves",
    brand: "Medicare",
    description: "Premium quality disposable surgical gloves.",
    metaTitle: "FCVH Surgical Gloves",
    metaDescription: "High quality surgical gloves for medical use.",
    images: [product1],
    sku: "SG001",
    hsn: "76443232",
    category: ["Medical Supplies"],
    defaultCategory: "Medical Supplies",
    price: 299,
    salePrice: 249,
    deliveryCharge: 50,
    gst: 5,
    quantity: 100,
    slug: "fcvh-surgical-gloves",
    referenceNo: "REF001",
    moq: 5,
    packing: "Box of 100",
    codAvailable: true,
    tags: ["gloves", "medical"],
    hasVariants: true,
    isPublished: true,
  },

  {
    id: "2",
    title: "Disposable Syringe 60ml",
    brand: "Romsons",
    description: "Sterile disposable syringe.",
    metaTitle: "Disposable Syringe 60ml",
    metaDescription: "Medical grade disposable syringe.",
    images: [product2],
    sku: "SYR060",
    hsn: "76443232",
    category: ["Medical Devices"],
    defaultCategory: "Medical Devices",
    price: 118,
    salePrice: 99,
    deliveryCharge: 40,
    gst: 5,
    quantity: 500,
    slug: "disposable-syringe-60ml",
    referenceNo: "REF002",
    moq: 10,
    packing: "Pack of 25",
    codAvailable: true,
    tags: ["syringe"],
    hasVariants: false,
    isPublished: true,
  },

  {
    id: "3",
    title: "Digital Thermometer",
    brand: "Omron",
    description: "Fast and accurate digital thermometer.",
    metaTitle: "Digital Thermometer",
    metaDescription: "Reliable digital thermometer.",
    images: [product3],
    sku: "THERM001",
    hsn: "76443232",
    category: ["Diagnostics"],
    defaultCategory: "Diagnostics",
    price: 499,
    salePrice: 449,
    deliveryCharge: 60,
    gst: 12,
    quantity: 80,
    slug: "digital-thermometer",
    referenceNo: "REF003",
    moq: 2,
    packing: "Single Unit",
    codAvailable: true,
    tags: ["thermometer"],
    hasVariants: false,
    isPublished: true,
  },

  {
    id: "4",
    title: "Pulse Oximeter",
    brand: "Dr Trust",
    description: "Accurate pulse and oxygen measurement.",
    metaTitle: "Pulse Oximeter",
    metaDescription: "Portable pulse oximeter.",
    images: [product1],
    sku: "POX001",
    hsn: "76443232",
    category: ["Diagnostics"],
    defaultCategory: "Diagnostics",
    price: 899,
    salePrice: 799,
    deliveryCharge: 70,
    gst: 12,
    quantity: 60,
    slug: "pulse-oximeter",
    referenceNo: "REF004",
    moq: 1,
    packing: "Single Unit",
    codAvailable: true,
    tags: ["oximeter"],
    hasVariants: false,
    isPublished: true,
  },

  {
    id: "5",
    title: "Antiseptic Solution 500ml",
    brand: "Dettol",
    description: "Multipurpose antiseptic liquid.",
    metaTitle: "Antiseptic Solution",
    metaDescription: "Kills germs and bacteria.",
    images: [product2],
    sku: "ANT500",
    hsn: "76443232",
    category: ["Pharmaceuticals"],
    defaultCategory: "Pharmaceuticals",
    price: 189,
    salePrice: 159,
    deliveryCharge: 30,
    gst: 5,
    quantity: 250,
    slug: "antiseptic-solution-500ml",
    referenceNo: "REF005",
    moq: 3,
    packing: "500ml Bottle",
    codAvailable: true,
    tags: ["antiseptic"],
    hasVariants: true,
    isPublished: true,
  },

  {
    id: "6",
    title: "Face Mask Pack",
    brand: "SafeCare",
    description: "3-layer surgical masks.",
    metaTitle: "Face Mask Pack",
    metaDescription: "Protection against dust and germs.",
    images: [product3],
    sku: "MASK50",
    hsn: "76443232",
    category: ["Medical Supplies"],
    defaultCategory: "Medical Supplies",
    price: 349,
    salePrice: 299,
    deliveryCharge: 40,
    gst: 5,
    quantity: 400,
    slug: "face-mask-pack",
    referenceNo: "REF006",
    moq: 10,
    packing: "Pack of 50",
    codAvailable: true,
    tags: ["mask"],
    hasVariants: true,
    isPublished: true,
  },

  {
    id: "7",
    title: "Examination Gloves Box",
    brand: "Medisure",
    description: "Latex examination gloves.",
    metaTitle: "Examination Gloves",
    metaDescription: "Comfortable and durable gloves.",
    images: [product1],
    sku: "GLV100",
    hsn: "76443232",
    category: ["Hospital Essentials"],
    defaultCategory: "Hospital Essentials",
    price: 599,
    salePrice: 549,
    deliveryCharge: 50,
    gst: 5,
    quantity: 150,
    slug: "examination-gloves-box",
    referenceNo: "REF007",
    moq: 5,
    packing: "Box of 100",
    codAvailable: true,
    tags: ["gloves"],
    hasVariants: true,
    isPublished: true,
  },
];

export const popularProducts = [
  {
    id: "1",
    name: "Romsons Toomay Syringe 60ml",
    price: "118",
    image: product1,
    badge: "sale",
    category: "Medical Devices",
  },
  {
    id: "2",
    name: "Romsons Toomay Syringe 60ml",
    price: "113",
    image: product2,
    badge: "hot",
    category: "Medical Supplies",
  },
  {
    id: "3",
    name: "Romsons Toomay Syringe 60ml",
    price: "2348",
    image: product1,
    badge: "10% off",
    category: "Diagnostics",
  },
  {
    id: "4",
    name: "Romsons Toomay Syringe 60ml",
    price: "335",
    image: product1,
    badge: "2 left",
    category: "Hospital Essentials",
  },
  {
    id: "5",
    name: "Romsons Toomay Syringe 60ml",
    price: "113",
    image: product3,
    badge: "10% off",
    category: "Pharmaceuticals",
  },
  {
    id: "6",
    name: "Romsons Toomay Syringe 60ml",
    price: "113",
    image: product3,
    badge: "hot",
    category: "Medical Supplies",
  },
  {
    id: "7",
    name: "Romsons Toomay Syringe 60ml",
    price: "2348",
    image: product3,
    badge: "sale",
    category: "Medical Supplies",
  },
  {
    id: "8",
    name: "Romsons Toomay Syringe 60ml",
    price: "335",
    image: product3,
    badge: "few left",
    category: "Medical Supplies",
  },
  {
    id: "9",
    name: "Romsons Toomay Syringe 60ml",
    price: "2348",
    image: product1,
    badge: "sale",
    category: "Medical Devices",
  },
  {
    id: "10",
    name: "Romsons Toomay Syringe 60ml",
    price: "113",
    image: product1,
    badge: "hot",
    category: "Medical Devices",
  },
  {
    id: "11",
    name: "Romsons Toomay Syringe 60ml",
    price: "2348",
    image: product1,
    badge: "sale",
    category: "Medical Devices",
  },
  {
    id: "12",
    name: "Romsons Toomay Syringe 60ml",
    price: "335",
    image: product1,
    category: "Medical supplies",
  },
  {
    id: "13",
    name: "Romsons Toomay Syringe 60ml",
    price: "335",
    image: product1,
    badge: "10% off",
    category: "Pharmaceuticals",
  },
  {
    id: "14",
    name: "Romsons Toomay Syringe 60ml",
    price: "113",
    image: product1,
    badge: "hot",
    category: "Pharmaceuticals",
  },
  {
    id: "15",
    name: "Romsons Toomay Syringe 60ml",
    price: "2348",
    image: product1,
    badge: "sale",
    category: "Pharmaceuticals",
  },
  {
    id: "16",
    name: "Romsons Toomay Syringe 60ml",
    price: "335",
    image: product1,
    category: "Pharmaceuticals",
  },
  {
    id: "17",
    name: "Romsons Toomay Syringe 60ml",
    price: "356",
    image: product1,
    badge: "10% off",
    category: "Diagnostics",
  },
  {
    id: "18",
    name: "Romsons Toomay Syringe 60ml",
    price: "335",
    image: product1,
    category: "Diagnostics",
  },
  {
    id: "19",
    name: "Romsons Toomay Syringe 60ml",
    price: "113",
    image: product1,
    badge: "hot",
    category: "Hospital Essentials",
  },
  {
    id: "20",
    name: "Romsons Toomay Syringe 60ml",
    price: "2348",
    image: product1,
    badge: "sale",
    category: "Hospital Essentials",
  },
  {
    id: "21",
    name: "Romsons Toomay Syringe 60ml",
    price: "7453",
    image: product2,
    badge: "sale",
    category: "Hospital Essentials",
  },
  {
    id: "22",
    name: "Romsons Toomay Syringe 60ml",
    price: "335",
    image: product2,
    category: "Diagnostics",
  },
  {
    id: "23",
    name: "Romsons Toomay Syringe 60ml",
    price: "113",
    image: product2,
    badge: "hot",
    category: "Diagnostics",
  },
  {
    id: "24",
    name: "Romsons Toomay Syringe 60ml",
    price: "2348",
    image: product2,
    badge: "sale",
    category: "Diagnostics",
  },
  {
    id: "25",
    name: "Romsons Toomay Syringe 60ml",
    price: "4563",
    image: product1,
    category: "Diagnostics",
  },
  {
    id: "26",
    name: "Romsons Toomay Syringe 60ml",
    price: "335",
    image: product1,
    badge: "best seller",
    category: "Pharmaceuticals",
  },
  {
    id: "27",
    name: "Romsons Toomay Syringe 60ml",
    price: "113",
    image: product1,
    badge: "hot",
    category: "Pharmaceuticals",
  },
  {
    id: "28",
    name: "Romsons Toomay Syringe 60ml",
    price: "2348",
    image: product1,
    badge: "sale",
    category: "Pharmaceuticals",
  },
];

export const popularProduct = [
  {
    id: "1",
    title: "FCVH Surgical Gloves",
    price: 299,
    salePrice: 249,
    image: product1,
    badge: "sale",
    category: "Medical Supplies",
  },
  {
    id: "2",
    title: "Disposable Syringe 60ml",
    price: 118,
    salePrice: 99,
    image: product2,
    badge: "hot",
    category: "Medical Devices",
  },
  {
    id: "3",
    title: "Digital Thermometer",
    price: 499,
    salePrice: 449,
    image: product3,
    badge: "10% off",
    category: "Diagnostics",
  },
  {
    id: "4",
    title: "Pulse Oximeter",
    price: 899,
    salePrice: 799,
    image: product1,
    badge: "best seller",
    category: "Diagnostics",
  },
  {
    id: "5",
    title: "Antiseptic Solution 500ml",
    price: 189,
    salePrice: 159,
    image: product2,
    badge: "sale",
    category: "Pharmaceuticals",
  },
  {
    id: "6",
    title: "Face Mask Pack",
    price: 349,
    salePrice: 299,
    image: product3,
    badge: "hot",
    category: "Medical Supplies",
  },
  {
    id: "7",
    title: "Examination Gloves Box",
    price: 599,
    salePrice: 549,
    image: product1,
    badge: "few left",
    category: "Hospital Essentials",
  },
];

export const testimonials = [
    {id:'1', image:test1, name:'Rahul Sharma', role:'customer',comment:'Medical & Surgical Solutions has made it really convenient to find healthcare products online. The website is easy to navigate, the product range is impressive, and ordering was a smooth experience.'},
    {id:'2', image:test2, name:'Amit Verma', role:'customer',comment:'I was looking for reliable surgical and healthcare supplies and found a good variety here. The product information was helpful, and the overall ordering experience was simple and convenient.'},
    {id:'3', image:test3, name:'Neha Singh', role:'customer',comment:'I really liked the wide selection of medical and healthcare products available on the website. It was easy to search for what I needed and place an order without any hassle.'},
    {id:'4', image:test4, name:'Rajendra Kumar', role:'customer',comment:'The website provides a good range of medical and surgical products in one place. I appreciate the convenience of being able to check products and order them online from home.'},
    {id:'5', image:test5, name:'Sunita Devi', role:'customer',comment:'Finding healthcare supplies online has become much easier with Medical & Surgical Solutions. The website is straightforward, and there are many products to choose from for different healthcare needs'},
    {id:'6', image:test6, name:'Arjun Mehta', role:'customer',comment:'A convenient platform for purchasing medical and surgical supplies online. I found the product categories easy to explore and the overall shopping experience quite smooth.'},
]

export const blogsdata = [
  {id:'1',image:blog1, name:'By Alicia Davis',date:'Aug 12, 2026', comment:'2.5k Comments', title:'There are many variations of passage available majority suffered.',description:'There are many variations available the majority have suffered alteration randomised words.'},
  {id:'2',image:blog1, name:'By Alicia Davis', date:'oct 15, 2025',comment:'3.1k Comments', title:'Contrary to popular belief making simply random text latin.',description:'There are many variations available the majority have suffered alteration randomised words.'},
  {id:'3',image:blog1, name:'By Alicia Davis',date:'nov 18, 2025', comment:'1.6k Comments', title:'If you are going use passage you need sure there middle text.',description:'There are many variations available the majority have suffered alteration randomised words.'},
   {id:'4',image:blog1, name:'By Alicia Davis', date:'jan 12, 2026',comment:'1.6k Comments', title:'If you are going use passage you need sure there middle text.',description:'There are many variations available the majority have suffered alteration randomised words.'}
]

export const instapost = [
  {id:'1', image:post1},
  {id:'2', image:post2},
  {id:'3', image:post3},
  {id:'4', image:post4},
  {id:'5', image:post5},
  {id:'6', image:post6}
]

export const contactinfo = [
  {id:'1', address:"402, Ground Floor, Near Bagga Link, Patparganj Industrial Area, Delhi-110092",phone:'+91 9643344588', email:'care@medicalsurgical.org', time:'Monday to Saturday', availability:'Available 24/7'}
]

export const stats = [
  {id:"1", image:rate, number:'11', sup:'k+', title:'Happy Customers'},
  {id:"2", image:premiumproducts, number:'15', sup:'k+', title:'Premium Products'},
  {id:"3", image:employee, number:'150', sup:'+', title:'Customer Support Team'},
  {id:"4", image:globalcustomer, number:'750', sup:'+', title:'Global Clients'},
]

export const team = [
   {id:"1", image:team1, name:'Rohit Kumar', position:'Distribution Head'},
   {id:"2", image:team2, name:'Rakesh Dubey', position:'Rakesh Dubey'},
   {id:"3", image:team3, name:'Manjeet Kaur', position:'Sales Admin'},
   {id:"4", image:team4, name:'Pankaj', position:'Sales Manager'},
   {id:"5", image:team5, name:'Kiran', position:'Online sales Co-Ordinator'},
   {id:"6", image:team6, name:'Ritik Thakur', position:'Account'},
]

export const faq = [
  {id:'1', question:'How to Sign Up on Medical Surgical Solutions website?', answer:'You will notice "Register or Sign In" on top right hand side of the Home Page. Click on it and fill in a simple form to register with us.'},
  {id:'2', question:'How to Sign Up on Medical Surgical Solutions website? How Long Will it Take To Get My Package?', answer:'You will notice "Register or Sign In" on top right hand side of the Home Page. Click on it and fill in a simple form to register with us. Depending on the Distance, you will receive your package within 7 working days.'},
  {id:'3', question:'How Do I Track My Order?', answer:'You can visit your order details page to track order.'},
  {id:'4', question:'How Do I Place an Order?', answer:"Sign In Search a product or navigate through the menu to locate a product and its details Add to Cart Edit quantity if required Click on Checkout Select Delivery and billing address. Select shipping method and payment option And you're done!"},
  {id:'5', question:'How Should I to Contact if I Have Any Queries?', answer:'You can visit our contact us page to get details on how to reach us'},
  {id:'6', question:'Do I Need an Account to Place an Order?', answer:'Yes! You required to create an account to place a order.'},
]